account_name     = "RCNZCWF"
organization_name = "UU37435"
user       = "Srikavya"
password   = "Srpu@7330691779"
role       = "ACCOUNTADMIN"
warehouse  = "COMPUTE_WH"
database   = "DEMO_DB"
schema     = "PUBLIC"
